"""empty message

Revision ID: 39c115654490
Revises: 42483f84cf4d
Create Date: 2018-04-14 13:54:05.229964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c115654490'
down_revision = '42483f84cf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'task id')
    op.add_column('tasks', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'approved')
    op.add_column('proposals', sa.Column('task id', sa.INTEGER(), server_default=sa.text('nextval(\'"proposals_task id_seq"\'::regclass)'), nullable=False))
    # ### end Alembic commands ###
