"""empty message

Revision ID: e2773e15846c
Revises: 39c115654490
Create Date: 2018-04-14 14:04:52.974926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2773e15846c'
down_revision = '39c115654490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('task', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'proposals', 'tasks', ['task'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'task')
    # ### end Alembic commands ###
